name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Create deployment directory
      run: mkdir -p deploy
      
    - name: Copy main index.html
      run: |
        if [ -f "index.html" ]; then
          cp index.html deploy/
          echo "Main index.html copied successfully"
        else
          echo "ERROR: Main index.html not found!"
          exit 1
        fi
      
    - name: Build Assessment Project
      continue-on-error: true
      run: |
        if [ -f "Assessment-1/Angular-StudentPortal-Assignment/package.json" ]; then
          cd Assessment-1/Angular-StudentPortal-Assignment
          if npm ci && npm run build -- --base-href=/AngularTraining/Assessment-1/Angular-StudentPortal-Assignment/; then
            mkdir -p ../../deploy/Assessment-1/Angular-StudentPortal-Assignment
            echo "Assessment-1 build successful"
            echo "=== DIST DIRECTORY STRUCTURE ==="
            find dist -type f | head -10
            echo "=== CHECKING DIRECTORIES ==="
            ls -la dist/
            if [ -d "dist/angular-student-portal-assignment" ]; then
              echo "Found dist/angular-student-portal-assignment, contents:"
              ls -la dist/angular-student-portal-assignment/
              cp -r dist/angular-student-portal-assignment/* ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/
              echo "Copied from dist/angular-student-portal-assignment/"
            else
              echo "No angular-student-portal-assignment folder, copying all dist contents"
              cp -r dist/* ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/
              echo "Copied from dist/"
            fi
            echo "=== FINAL DEPLOYMENT CONTENTS ==="
            ls -la ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/
            echo "=== CHECKING FOR INDEX.HTML ==="
            find ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/ -name "index.html" -type f
            echo "Assessment-1 deployed successfully"
          else
            echo "Assessment-1 build failed, skipping deployment"
          fi
          cd ../..
        fi
        
    - name: Build Day1 Projects
      run: |
        # Copy static projects
        mkdir -p deploy/Day1
        if [ -d "Day1/Hangman" ]; then
          cp -r Day1/Hangman deploy/Day1/
          echo "Day1/Hangman copied successfully"
        fi
        if [ -d "Day1/ts-app" ]; then
          cp -r Day1/ts-app deploy/Day1/
          echo "Day1/ts-app copied successfully"
        fi
        
        # Build Angular projects
        if [ -f "Day1/portfolio/package.json" ]; then
          cd Day1/portfolio
          if npm ci && npm run build -- --base-href=/AngularTraining/Day1/portfolio/; then
            mkdir -p ../../deploy/Day1/portfolio
            echo "Day1/portfolio build successful"
            if [ -d "dist/portfolio/browser" ]; then
              cp -r dist/portfolio/browser/* ../../deploy/Day1/portfolio/
            elif [ -d "dist/portfolio" ]; then
              cp -r dist/portfolio/* ../../deploy/Day1/portfolio/
            else
              cp -r dist/* ../../deploy/Day1/portfolio/
            fi
            echo "Day1/portfolio deployed successfully"
          else
            echo "Day1/portfolio build failed, skipping deployment"
          fi
          cd ../..
        fi
        
        if [ -f "Day1/Sample-Project/package.json" ]; then
          cd Day1/Sample-Project
          if npm ci && npm run build -- --base-href=/AngularTraining/Day1/Sample-Project/; then
            mkdir -p ../../deploy/Day1/Sample-Project
            echo "Day1/Sample-Project build successful"
            if [ -d "dist/sample-project/browser" ]; then
              cp -r dist/sample-project/browser/* ../../deploy/Day1/Sample-Project/
            elif [ -d "dist/sample-project" ]; then
              cp -r dist/sample-project/* ../../deploy/Day1/Sample-Project/
            else
              cp -r dist/* ../../deploy/Day1/Sample-Project/
            fi
            echo "Day1/Sample-Project deployed successfully"
          else
            echo "Day1/Sample-Project build failed, skipping deployment"
          fi
          cd ../..
        fi
        
    - name: Build Day2 Projects
      continue-on-error: true
      run: |
        if [ -f "Day2/prime-app/package.json" ]; then
          cd Day2/prime-app
          if npm ci && npm run build -- --base-href=/AngularTraining/Day2/prime-app/; then
            mkdir -p ../../deploy/Day2/prime-app
            echo "Day2/prime-app build successful"
            if [ -d "dist/prime-app/browser" ]; then
              cp -r dist/prime-app/browser/* ../../deploy/Day2/prime-app/
            elif [ -d "dist/prime-app" ]; then
              cp -r dist/prime-app/* ../../deploy/Day2/prime-app/
            else
              cp -r dist/* ../../deploy/Day2/prime-app/
            fi
            echo "Day2/prime-app deployed successfully"
          else
            echo "Day2/prime-app build failed, skipping deployment"
          fi
          cd ../..
        fi
        
    - name: Build Day3 Projects
      continue-on-error: true
      run: |
        if [ -f "Day3/portfolio/package.json" ]; then
          cd Day3/portfolio
          if npm ci && npm run build -- --base-href=/AngularTraining/Day3/portfolio/; then
            mkdir -p ../../deploy/Day3/portfolio
            echo "Day3/portfolio build successful"
            if [ -d "dist/portfolio/browser" ]; then
              cp -r dist/portfolio/browser/* ../../deploy/Day3/portfolio/
            elif [ -d "dist/portfolio" ]; then
              cp -r dist/portfolio/* ../../deploy/Day3/portfolio/
            else
              cp -r dist/* ../../deploy/Day3/portfolio/
            fi
            echo "Day3/portfolio deployed successfully"
          else
            echo "Day3/portfolio build failed, skipping deployment"
          fi
          cd ../..
        fi
        
    - name: Build Day4 Projects
      continue-on-error: true
      run: |
        if [ -f "Day4/Sample-Project/package.json" ]; then
          cd Day4/Sample-Project
          if npm ci && npm run build -- --base-href=/AngularTraining/Day4/Sample-Project/; then
            mkdir -p ../../deploy/Day4/Sample-Project
            echo "Day4/Sample-Project build successful"
            if [ -d "dist/sample-project/browser" ]; then
              cp -r dist/sample-project/browser/* ../../deploy/Day4/Sample-Project/
            elif [ -d "dist/sample-project" ]; then
              cp -r dist/sample-project/* ../../deploy/Day4/Sample-Project/
            else
              cp -r dist/* ../../deploy/Day4/Sample-Project/
            fi
            echo "Day4/Sample-Project deployed successfully"
          else
            echo "Day4/Sample-Project build failed, skipping deployment"
          fi
          cd ../..
        fi
        
    - name: Build Day5 Projects
      continue-on-error: true
      run: |
        if [ -f "Day5/Sample-Project/package.json" ]; then
          cd Day5/Sample-Project
          if npm ci --legacy-peer-deps && npm run build -- --base-href=/AngularTraining/Day5/Sample-Project/; then
            mkdir -p ../../deploy/Day5/Sample-Project
            echo "Day5/Sample-Project build successful"
            if [ -d "dist/sample-project/browser" ]; then
              cp -r dist/sample-project/browser/* ../../deploy/Day5/Sample-Project/
            elif [ -d "dist/sample-project" ]; then
              cp -r dist/sample-project/* ../../deploy/Day5/Sample-Project/
            else
              cp -r dist/* ../../deploy/Day5/Sample-Project/
            fi
            echo "Day5/Sample-Project deployed successfully"
          else
            echo "Day5/Sample-Project build failed, skipping deployment"
          fi
          cd ../..
        fi
        
    - name: Create 404.html
      run: |
        echo '<!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Redirecting...</title>
          <script>
            window.location.href = "/AngularTraining/";
          </script>
        </head>
        <body>
          <p>Redirecting to <a href="/AngularTraining/">main page</a>...</p>
        </body>
        </html>' > deploy/404.html
      
    - name: List deployment contents
      run: |
        echo "Final deployment directory structure:"
        find deploy -type f | head -30
        echo ""
        echo "Deployment directories:"
        find deploy -type d | sort
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        force_orphan: true
