name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create deployment directory
      run: mkdir -p deploy
      
    - name: Copy main index.html
      run: cp index.html deploy/
      
    - name: Build Assessment Project
      run: |
        if [ -f "Assessment-1/Angular-StudentPortal-Assignment/package.json" ]; then
          cd Assessment-1/Angular-StudentPortal-Assignment
          npm ci
          npm run build -- --base-href=/AngularTraining/Assessment-1/Angular-StudentPortal-Assignment/
          mkdir -p ../../deploy/Assessment-1/Angular-StudentPortal-Assignment
          if [ -d "dist/angular-student-portal-assignment" ]; then
            cp dist/angular-student-portal-assignment/index.html ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/
            cp -r dist/angular-student-portal-assignment/*.js ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/ 2>/dev/null || true
            cp -r dist/angular-student-portal-assignment/*.css ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/ 2>/dev/null || true
            cp -r dist/angular-student-portal-assignment/assets ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/ 2>/dev/null || true
            cp -r dist/angular-student-portal-assignment/favicon.ico ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/ 2>/dev/null || true
          else
            find dist -name "*.html" -o -name "*.js" -o -name "*.css" -o -name "favicon.ico" | xargs -I {} cp {} ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/
            cp -r dist/assets ../../deploy/Assessment-1/Angular-StudentPortal-Assignment/ 2>/dev/null || true
          fi
          cd ../..
        fi
        
    - name: Build Day1 Projects
      run: |
        # Copy static projects
        mkdir -p deploy/Day1
        if [ -d "Day1/Hangman" ]; then
          cp -r Day1/Hangman deploy/Day1/
        fi
        if [ -d "Day1/ts-app" ]; then
          cp -r Day1/ts-app deploy/Day1/
        fi
        
        # Build Angular projects
        if [ -f "Day1/portfolio/package.json" ]; then
          cd Day1/portfolio
          npm ci
          npm run build -- --base-href=/AngularTraining/Day1/portfolio/
          mkdir -p ../../deploy/Day1/portfolio
          if [ -d "dist/portfolio" ]; then
            cp -r dist/portfolio/* ../../deploy/Day1/portfolio/
          else
            cp -r dist/* ../../deploy/Day1/portfolio/
          fi
          cd ../..
        fi
        
        if [ -f "Day1/Sample-Project/package.json" ]; then
          cd Day1/Sample-Project
          npm ci
          npm run build -- --base-href=/AngularTraining/Day1/Sample-Project/
          mkdir -p ../../deploy/Day1/Sample-Project
          if [ -d "dist/Sample-Project" ]; then
            cp -r dist/Sample-Project/* ../../deploy/Day1/Sample-Project/
          elif [ -d "dist/sample-project" ]; then
            cp -r dist/sample-project/* ../../deploy/Day1/Sample-Project/
          else
            cp -r dist/* ../../deploy/Day1/Sample-Project/
          fi
          cd ../..
        fi
        
    - name: Build Day2 Projects
      run: |
        if [ -f "Day2/prime-app/package.json" ]; then
          cd Day2/prime-app
          npm ci
          npm run build -- --base-href=/AngularTraining/Day2/prime-app/
          mkdir -p ../../deploy/Day2/prime-app
          if [ -d "dist/prime-app" ]; then
            cp -r dist/prime-app/* ../../deploy/Day2/prime-app/
          else
            cp -r dist/* ../../deploy/Day2/prime-app/
          fi
          cd ../..
        fi
        
    - name: Build Day3 Projects
      run: |
        if [ -f "Day3/portfolio/package.json" ]; then
          cd Day3/portfolio
          npm ci
          npm run build -- --base-href=/AngularTraining/Day3/portfolio/
          mkdir -p ../../deploy/Day3/portfolio
          if [ -d "dist/portfolio" ]; then
            cp -r dist/portfolio/* ../../deploy/Day3/portfolio/
          else
            cp -r dist/* ../../deploy/Day3/portfolio/
          fi
          cd ../..
        fi
        
    - name: Build Day4 Projects
      run: |
        if [ -f "Day4/Sample-Project/package.json" ]; then
          cd Day4/Sample-Project
          npm ci
          npm run build -- --base-href=/AngularTraining/Day4/Sample-Project/
          mkdir -p ../../deploy/Day4/Sample-Project
          if [ -d "dist/Sample-Project" ]; then
            cp -r dist/Sample-Project/* ../../deploy/Day4/Sample-Project/
          elif [ -d "dist/sample-project" ]; then
            cp -r dist/sample-project/* ../../deploy/Day4/Sample-Project/
          else
            cp -r dist/* ../../deploy/Day4/Sample-Project/
          fi
          cd ../..
        fi
        
    - name: Build Day5 Projects
      run: |
        if [ -f "Day5/Sample-Project/package.json" ]; then
          cd Day5/Sample-Project
          npm ci
          npm run build -- --base-href=/AngularTraining/Day5/Sample-Project/
          mkdir -p ../../deploy/Day5/Sample-Project
          if [ -d "dist/Sample-Project" ]; then
            cp -r dist/Sample-Project/* ../../deploy/Day5/Sample-Project/
          elif [ -d "dist/sample-project" ]; then
            cp -r dist/sample-project/* ../../deploy/Day5/Sample-Project/
          else
            cp -r dist/* ../../deploy/Day5/Sample-Project/
          fi
          cd ../..
        fi
        
    - name: Create 404.html
      run: |
        echo '<!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Redirecting...</title>
          <script>
            window.location.href = "/AngularTraining/";
          </script>
        </head>
        <body>
          <p>Redirecting to <a href="/AngularTraining/">main page</a>...</p>
        </body>
        </html>' > deploy/404.html
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        cname: false
